export default [
  {
    date: "20220706",
    actions: [
      {
        ref: "NEN7F6C",
        trxn: "56043c10-4a31-4be6-bfe9-a818f8f75274",
        type: "Debit",
        status: "Success",
        party: "Jenkins Group",
        amount: "GHS3,282.91",
        narrative: "Nulla vero et sit ut enim incidunt.",
      },
      {
        ref: "ydTFq5K",
        trxn: "81650480-6700-4dc4-aab3-a71b4a8eb280",
        type: "Debit",
        status: "Success",
        party: "Thompson Inc",
        amount: "GHS1,157.26",
        narrative:
          "Sequi voluptas molestiae commodi id doloribus qui dolorem perferendis.",
      },
      {
        ref: "F4PnCbi",
        trxn: "15b08d7d-0530-4938-bbfd-d84d41fe53dc",
        type: "Reversal",
        status: "Pending",
        party: "Wehner, Wintheiser and Terry",
        amount: "GHS3,734.92",
        narrative:
          "Inventore atque maxime odio nulla et consectetur ullam aperiam eum.",
      },
      {
        ref: "6GtLAPu",
        trxn: "adb294d2-1119-4454-a90b-0220bdb0c7f1",
        type: "Credit",
        status: "Pending",
        party: "Schmidt - Cremin",
        amount: "GHS3,475.14",
        narrative: "Nobis veniam est distinctio.",
      },
    ],
  },
  {
    date: "20220705",
    actions: [
      {
        ref: "UbL2n3L",
        trxn: "2397cfc5-7e7a-426c-b9af-f626370395a2",
        type: "Reversal",
        status: "Failed",
        party: "Ryan Inc",
        amount: "GHS3,673.05",
        narrative: "Aut a non a eius dolorum.",
      },
      {
        ref: "ZfXkSH0",
        trxn: "871dde64-778e-449a-86dd-006919ed3861",
        type: "Reversal",
        status: "Success",
        party: "Bergnaum, Hayes and Streich",
        amount: "GHS2,901.27",
        narrative: "Rerum voluptatum ab et.",
      },
    ],
  },
  {
    date: "20220704",
    actions: [
      {
        ref: "BSZRjUe",
        trxn: "2f0dd647-274d-4407-8003-4b31bb0f0853",
        type: "Credit",
        status: "Pending",
        party: "Schowalter LLC",
        amount: "GHS4,778.03",
        narrative: "Sit qui quidem esse quia eius atque sed.",
      },
      {
        ref: "zR1QLoX",
        trxn: "58d2e58d-8da4-4f4f-bea6-21bdb1f44d03",
        type: "Credit",
        status: "Pending",
        party: "Mitchell - Von",
        amount: "GHS938.58",
        narrative:
          "Voluptas nobis occaecati reiciendis velit accusantium dignissimos delectus sint magni.",
      },
    ],
  },
  {
    date: "20220703",
    actions: [
      {
        ref: "blqDzAJ",
        trxn: "bc436413-3643-47d1-92e5-ce82d1458e4e",
        type: "Debit",
        status: "Failed",
        party: "Dickinson, Walker and Corwin",
        amount: "GHS9,205.54",
        narrative: "Qui quas quis excepturi suscipit.",
      },
      {
        ref: "v02tmWW",
        trxn: "8e89142b-1ff0-4d85-9f69-f01cde613f34",
        type: "Debit",
        status: "Failed",
        party: "Kemmer, Davis and Gerhold",
        amount: "GHS1,668.42",
        narrative: "Ea suscipit esse.",
      },
      {
        ref: "hElJ7jy",
        trxn: "5a3f4bf1-de9a-4b01-a38f-55c5095b509e",
        type: "Reversal",
        status: "Success",
        party: "Lindgren, Nienow and Bogan",
        amount: "GHS6,325.97",
        narrative: "Nulla eveniet esse.",
      },
      {
        ref: "l1B7fI1",
        trxn: "fd28523b-45d0-46be-a171-804c84aa74c6",
        type: "Debit",
        status: "Pending",
        party: "Monahan - Ferry",
        amount: "GHS8,124.78",
        narrative:
          "Praesentium cumque est voluptatem itaque labore magni rerum.",
      },
      {
        ref: "EteoFlD",
        trxn: "a8cee36e-eeb5-4ecf-88c7-1862a093b349",
        type: "Credit",
        status: "Success",
        party: "Romaguera and Sons",
        amount: "GHS7,412.64",
        narrative:
          "Molestiae mollitia incidunt fuga vitae nesciunt omnis laborum.",
      },
    ],
  },
  {
    date: "20220702",
    actions: [
      {
        ref: "Isq78Tp",
        trxn: "31ef96bc-3469-449a-ad89-8a78ac78b2bb",
        type: "Debit",
        status: "Success",
        party: "O'Keefe Group",
        amount: "GHS5,164.36",
        narrative: "Aut mollitia ut quaerat blanditiis vel fugit dolores.",
      },
      {
        ref: "g1zWrqB",
        trxn: "2cbad83e-f038-4a1c-a9c4-1a3d5b5b28a1",
        type: "Reversal",
        status: "Failed",
        party: "Konopelski, O'Keefe and Koepp",
        amount: "GHS6,086.76",
        narrative: "Quibusdam nulla error ipsa rerum.",
      },
      {
        ref: "dLt1mfR",
        trxn: "ea4aa016-cbd8-4901-bd3f-93ed2ac8df95",
        type: "Reversal",
        status: "Failed",
        party: "Larkin - Ratke",
        amount: "GHS1,202.04",
        narrative: "Adipisci ut ipsam quaerat sed officiis et dolor nemo.",
      },
      {
        ref: "X0nRJc8",
        trxn: "9439f267-e8de-42ee-a920-2dc3e2bfbbd2",
        type: "Debit",
        status: "Failed",
        party: "Hagenes, Heidenreich and Koepp",
        amount: "GHS5,495.78",
        narrative: "Enim perspiciatis iste quam.",
      },
      {
        ref: "eeBresG",
        trxn: "1b9f7120-a9ea-4bdc-89c3-5cee6146b94e",
        type: "Debit",
        status: "Pending",
        party: "Cremin - Pfannerstill",
        amount: "GHS7,226.86",
        narrative: "Autem quos ullam dolorem.",
      },
      {
        ref: "vX3ARHw",
        trxn: "3a915ea4-98bf-4ef5-9184-23fd49cd4394",
        type: "Credit",
        status: "Success",
        party: "Mayert - Jaskolski",
        amount: "GHS5,492.52",
        narrative: "Eum doloribus doloribus libero fugit nihil aut.",
      },
      {
        ref: "qa2RNkI",
        trxn: "e88af4a9-c346-4789-86c8-b7909744cac1",
        type: "Debit",
        status: "Pending",
        party: "Sauer LLC",
        amount: "GHS9,551.00",
        narrative: "Et enim nostrum autem odio aspernatur.",
      },
    ],
  },
  {
    date: "20220701",
    actions: [
      {
        ref: "2dzkwKd",
        trxn: "af1b3fea-a5b5-4d21-9007-9e119b777638",
        type: "Debit",
        status: "Pending",
        party: "Jacobi, Adams and Bednar",
        amount: "GHS1,200.46",
        narrative: "Aliquam necessitatibus quisquam.",
      },
      {
        ref: "EqMe0lf",
        trxn: "72245732-a4cf-47f3-a616-d1c821c8b972",
        type: "Debit",
        status: "Success",
        party: "Rice - Cronin",
        amount: "GHS6,410.01",
        narrative: "At libero et vitae voluptatibus voluptatem nobis ab.",
      },
      {
        ref: "0m2AtOD",
        trxn: "d27d208c-6036-46ca-80b2-147f6ef68009",
        type: "Reversal",
        status: "Success",
        party: "Considine - Turcotte",
        amount: "GHS3,097.44",
        narrative: "Sed eligendi debitis modi animi ut.",
      },
      {
        ref: "8VxC4DA",
        trxn: "9529dae6-66a7-4d31-8513-7456c74a0dd7",
        type: "Reversal",
        status: "Success",
        party: "Upton, Bradtke and Hills",
        amount: "GHS5,261.08",
        narrative: "Maiores ut saepe voluptatum dolor omnis enim.",
      },
      {
        ref: "UWYtIRJ",
        trxn: "a5443f1c-afa3-4eea-bdf0-b0db5e4a0bab",
        type: "Reversal",
        status: "Success",
        party: "Carter and Sons",
        amount: "GHS4,798.80",
        narrative: "Beatae expedita dolores quaerat qui possimus dolore.",
      },
      {
        ref: "lIFzYFo",
        trxn: "c3b11200-2739-4736-9c58-0c3886dba414",
        type: "Reversal",
        status: "Pending",
        party: "O'Keefe Group",
        amount: "GHS9,687.61",
        narrative: "Vero consequuntur error dolorem vitae qui.",
      },
      {
        ref: "2Rw1Mrk",
        trxn: "304913a0-02a6-42bf-a871-bf06a598e630",
        type: "Credit",
        status: "Success",
        party: "Rowe - Fritsch",
        amount: "GHS6,658.41",
        narrative:
          "Et quisquam nam quasi quisquam repellendus perferendis laborum doloremque vero.",
      },
    ],
  },
];
