const data = [
  {
    id: "0",
    type: "Credit",
    status: "Pending",
    party: "Abshire - Fisher",
    amount: "GHS2,944.50",
    narrative: "Omnis id eaque placeat illum voluptatem.",
    logId: "6",
  },
  {
    id: "1",
    type: "Debit",
    status: "Pending",
    party: "Schultz - Considine",
    amount: "GHS850.57",
    narrative: "Minus deleniti et minus occaecati.",
    logId: "6",
  },
  {
    id: "2",
    type: "Reversal",
    status: "Success",
    party: "Dooley, Dare and Baumbach",
    amount: "GHS9,244.69",
    narrative: "Debitis praesentium inventore esse et et ad rerum fugit ut.",
    logId: "1",
  },
  {
    id: "3",
    type: "Debit",
    status: "Success",
    party: "Kassulke, Collier and Howe",
    amount: "GHS3,470.71",
    narrative: "In aspernatur accusantium.",
    logId: "2",
  },
  {
    id: "4",
    type: "Reversal",
    status: "Pending",
    party: "Williamson Inc",
    amount: "GHS4,335.06",
    narrative: "Ab consequatur itaque ad adipisci.",
    logId: "2",
  },
  {
    id: "5",
    type: "Debit",
    status: "Failed",
    party: "Rosenbaum Inc",
    amount: "GHS857.52",
    narrative:
      "Id eveniet modi dolore fugit voluptas nemo aut molestias tenetur.",
    logId: "6",
  },
  {
    id: "6",
    type: "Debit",
    status: "Pending",
    party: "Streich, Gerhold and Borer",
    amount: "GHS5,252.34",
    narrative: "Consequatur at quod vel nihil.",
    logId: "1",
  },
  {
    id: "7",
    type: "Debit",
    status: "Pending",
    party: "Barrows Inc",
    amount: "GHS7,697.69",
    narrative: "Tempora enim sunt consequatur praesentium.",
    logId: "4",
  },
  {
    id: "8",
    type: "Reversal",
    status: "Pending",
    party: "Roob - Huels",
    amount: "GHS726.31",
    narrative: "Saepe soluta quidem libero aut blanditiis autem.",
    logId: "2",
  },
  {
    id: "9",
    type: "Reversal",
    status: "Pending",
    party: "Ziemann - Wiegand",
    amount: "GHS1,802.30",
    narrative: "Repellendus eum quaerat ducimus omnis.",
    logId: "2",
  },
  {
    id: "10",
    type: "Reversal",
    status: "Success",
    party: "Bechtelar - Wilkinson",
    amount: "GHS2,376.08",
    narrative: "Quidem magnam impedit sed facilis error.",
    logId: "1",
  },
  {
    id: "11",
    type: "Reversal",
    status: "Pending",
    party: "Kunde - Nicolas",
    amount: "GHS3,559.20",
    narrative:
      "Dolorem est accusantium temporibus accusantium id molestiae modi cum unde.",
    logId: "6",
  },
  {
    id: "12",
    type: "Debit",
    status: "Pending",
    party: "Keebler - Tremblay",
    amount: "GHS749.54",
    narrative: "Modi delectus quae praesentium.",
    logId: "3",
  },
  {
    id: "13",
    type: "Debit",
    status: "Failed",
    party: "Miller, Prosacco and McClure",
    amount: "GHS3,257.40",
    narrative: "Et ipsum rem veniam eius voluptatem.",
    logId: "1",
  },
  {
    id: "14",
    type: "Debit",
    status: "Failed",
    party: "Glover, West and Jast",
    amount: "GHS9,377.21",
    narrative: "Ipsum quasi molestiae et accusantium dolor rerum.",
    logId: "3",
  },
  {
    id: "15",
    type: "Debit",
    status: "Failed",
    party: "Ferry Group",
    amount: "GHS2,920.63",
    narrative:
      "Eos totam rerum optio illum quibusdam iusto ad consequatur velit.",
    logId: "2",
  },
  {
    id: "16",
    type: "Reversal",
    status: "Pending",
    party: "Braun, Bradtke and Bailey",
    amount: "GHS3,065.49",
    narrative: "Non natus ut facilis quisquam doloremque nam facilis.",
    logId: "1",
  },
  {
    id: "17",
    type: "Credit",
    status: "Pending",
    party: "Wunsch, Walsh and Mueller",
    amount: "GHS3,552.02",
    narrative: "Temporibus ab quis et dolores inventore quas nihil veritatis.",
    logId: "2",
  },
  {
    id: "18",
    type: "Credit",
    status: "Success",
    party: "Beahan Group",
    amount: "GHS4,738.63",
    narrative: "Quod et sed.",
    logId: "3",
  },
  {
    id: "19",
    type: "Debit",
    status: "Pending",
    party: "Osinski Group",
    amount: "GHS6,771.15",
    narrative:
      "Hic voluptas voluptatem possimus rerum maxime vel est adipisci.",
    logId: "5",
  },
  {
    id: "20",
    type: "Credit",
    status: "Success",
    party: "Steuber and Sons",
    amount: "GHS5,410.84",
    narrative: "Ut nisi aut et necessitatibus dolor deserunt.",
    logId: "1",
  },
  {
    id: "21",
    type: "Reversal",
    status: "Failed",
    party: "Lynch - Keebler",
    amount: "GHS916.86",
    narrative: "Aliquid enim dicta veritatis.",
    logId: "3",
  },
  {
    id: "22",
    type: "Credit",
    status: "Pending",
    party: "Larkin - Gottlieb",
    amount: "GHS7,448.45",
    narrative: "Iure porro quis dignissimos ut sit similique nemo et.",
    logId: "4",
  },
  {
    id: "23",
    type: "Credit",
    status: "Failed",
    party: "Greenfelder, DuBuque and Gleason",
    amount: "GHS8,034.76",
    narrative: "Totam et repellat explicabo magnam tempora sed rerum in sed.",
    logId: "5",
  },
  {
    id: "24",
    type: "Debit",
    status: "Failed",
    party: "Heidenreich - Kunde",
    amount: "GHS2,124.99",
    narrative: "Maiores quo debitis ea.",
    logId: "1",
  },
  {
    id: "25",
    type: "Debit",
    status: "Success",
    party: "Blanda, Balistreri and Wintheiser",
    amount: "GHS4,573.09",
    narrative: "Nulla sunt beatae fuga quia qui cum neque.",
    logId: "3",
  },
  {
    id: "26",
    type: "Reversal",
    status: "Pending",
    party: "Rosenbaum, Gleichner and Murphy",
    amount: "GHS7,052.48",
    narrative: "Sequi ipsum at corrupti quia nobis nihil corrupti et.",
    logId: "6",
  },
];

export default data;
